# CREATE

### Add a new department
POST http://localhost:8200/api/department
Content-Type: application/json

{
    "DepartmentID": "D6",
    "DepartmentName": "It",
    "MaximumOvertime": "08:00:00"
}

# READ
 
### Fetch all the department available 
GET http://localhost:8200/api/department/all

### Fetch an department by id
GET http://localhost:8200/api/department/47651ac7-87f6-478b-b42e-623e53f5890f

# UPDATE

### Update one department by id
PUT http://localhost:8200/api/department/47651ac7-87f6-478b-b42e-623e53f5890f
Content-Type: application/json

{
    "DepartmentName": "Its",
    "MaximumOvertime": "08:00:00"
}

# DELETE

### Delete an instance of department
DELETE http://localhost:8200/api/department/47651ac7-87f6-478b-b42e-623e53f5890f