# Registering a new employee
###
POST  http://localhost:8200/api/employee/register
Content-Type: application/json

{
    "First_name":"Lewis",
    "Last_name":"Kemboi",
    "Email_address":"kemboilewis6@gmail.com",
    "Password":"@Usr0123!",
    "Contact_information":"0701282658",
    "Gender":"Male",
    "Admin_role":"Admin",
    "Date_of_Birth":"1997-07-07",
    "Country":"Kenya",
    "City":"Nyeri",
    "Street":"3948 NYR str",
    "Postal_code":"94276",
    "Profile_url":""
}

# Log in the employee and provide token
###
POST  http://localhost:8200/api/employee/loginEmployee
Content-Type:  application/json

{
    "Email_address":"kemboilewis@example.com",
    "Password":"@Usr0123!"
}

# Fetching all the employees
###
GET http://localhost:8200/api/employee/fetchall

### /employee/fetchall/details
GET http://localhost:8200/api/employee/fetchall/details

### /employee/leave/position/department
GET http://localhost:8200/api/employee/leave/position/department

### /employee/count
GET http://localhost:8200/api/employee/count

# Fetching one employee by passing the employeeID
###
GET http://localhost:8200/api/employee/fetchByEmail/kemboilewis@example.com

# Delete an employee by email address
###
DELETE http://localhost:8200/api/employee/deleteByEmail/alice@example.com

EmployeeID,First_name,Last_name,Email_address,Password,Contact_information,Gender,Admin_role,Date_of_Birth,Country,City,Street,Postal_code
