# CREATE

### Add a new payroll
POST http://localhost:8200/api/payroll
Content-Type: application/json

{
    "PayrollID": "PR006",
    "EmployeeID": "1",
    "GrossPay": 5000,
    "DeductionID": "417abe26-b47f-47ff-a3c4-7a820bf357a5",
    "NetPay": 4000,
    "OvertimePay": 200,
    "Advance": 1000
}

# READ

### Fetch all the payroll available 
GET http://localhost:8200/api/payroll/all

### Fetch an payroll by id
GET http://localhost:8200/api/payroll/d546d419-0997-443b-ad13-2ab0f97c6b2f

# UPDATE

### Update one payroll by id
PUT http://localhost:8200/api/payroll/d546d419-0997-443b-ad13-2ab0f97c6b2f
Content-Type: application/json

{
    "EmployeeID": "1",
    "GrossPay": 5000,
    "DeductionID": "417abe26-b47f-47ff-a3c4-7a820bf357a5",
    "NetPay": 4000,
    "OvertimePay": 200,
    "Advance": 1050
}

# DELETE

### Delete an instance of payroll
DELETE http://localhost:8200/api/payroll/d546d419-0997-443b-ad13-2ab0f97c6b2f