# CREATE SCHEDULE
###
POST http://localhost:8200/api/schedule
Content-Type: application/json

{
    "EmailAddress":"john@example.com",
    "ScheduleName":"Night Shift",
    "CheckIn":"08:00:00",
    "CheckOut":"19:00:00",
    "Days":"testing1234555r"
}

# READ SCHEDULE
###
GET http://localhost:8200/api/schedule/all

###
GET http://localhost:8200/api/schedule/allEmployeesWithSchedules

###
GET  http://localhost:8200/api/schedule/2d6efa5b-0890-4d87-a89e-ebaa5e8e6e51

# UPDATE SCHEDULE
###
PUT  http://localhost:8200/api/schedule/0bef60ab-30b3-497f-a286-dcc3b7cfac10
Content-Type: application/json

{
    "ScheduleName":"Check",
    "CheckIn":"1900-01-01 08:00:00.000",
    "CheckOut":"1900-01-01 09:00:00.000",
    "DAYS":"Wednesday"
}

# DELETE SCHEDULE
###
DELETE  http://localhost:8200/api/schedule/80823470-6845-453b-ae28-d6bdddbbc8fd